<?php
/**
 * Shared OpenStax/OER catalog definitions for AHSA course generation and verification.
 */

defined( 'ABSPATH' ) || exit;

/**
 * Get full course catalog definitions.
 *
 * @return array[]
 */
function llms_openstax_course_catalog_definitions() {
	return array(
		// High school core (9-12).
		array( 'subject' => 'English 1', 'grade' => 9, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 9-10' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 1', 'grade' => 9, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 9-10' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Algebra 1', 'grade' => 9, 'semester' => 1, 'book' => 'Algebra and Trigonometry 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'B.E.S.T. MATH Algebra 1' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Algebra 1', 'grade' => 9, 'semester' => 2, 'book' => 'Algebra and Trigonometry 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'B.E.S.T. MATH Algebra 1' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Biology 1', 'grade' => 10, 'semester' => 1, 'book' => 'Biology 2e', 'ncaa_area' => 'Natural/Physical Science', 'standards' => array( 'NGSSS Biology 1' ), 'course_track' => 'Science', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Biology 1', 'grade' => 10, 'semester' => 2, 'book' => 'Biology 2e', 'ncaa_area' => 'Natural/Physical Science', 'standards' => array( 'NGSSS Biology 1' ), 'course_track' => 'Science', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Geometry', 'grade' => 10, 'semester' => 1, 'book' => 'Precalculus 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'B.E.S.T. MATH Geometry' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Geometry', 'grade' => 10, 'semester' => 2, 'book' => 'Precalculus 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'B.E.S.T. MATH Geometry' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 2', 'grade' => 10, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 9-10' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 2', 'grade' => 10, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 9-10' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'World History', 'grade' => 10, 'semester' => 1, 'book' => 'World History, Volume 1', 'ncaa_area' => 'Social Science', 'standards' => array( 'Florida World History 9-12' ), 'course_track' => 'Social Studies', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'World History', 'grade' => 10, 'semester' => 2, 'book' => 'World History, Volume 2', 'ncaa_area' => 'Social Science', 'standards' => array( 'Florida World History 9-12' ), 'course_track' => 'Social Studies', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Algebra 2', 'grade' => 11, 'semester' => 1, 'book' => 'Algebra and Trigonometry 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'B.E.S.T. MATH Algebra 2' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Algebra 2', 'grade' => 11, 'semester' => 2, 'book' => 'Algebra and Trigonometry 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'B.E.S.T. MATH Algebra 2' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Chemistry 1', 'grade' => 11, 'semester' => 1, 'book' => 'Chemistry 2e', 'ncaa_area' => 'Natural/Physical Science', 'standards' => array( 'Florida Chemistry 1 9-12' ), 'course_track' => 'Science', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Chemistry 1', 'grade' => 11, 'semester' => 2, 'book' => 'Chemistry 2e', 'ncaa_area' => 'Natural/Physical Science', 'standards' => array( 'Florida Chemistry 1 9-12' ), 'course_track' => 'Science', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 3', 'grade' => 11, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 11-12' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 3', 'grade' => 11, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 11-12' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'US History', 'grade' => 11, 'semester' => 1, 'book' => 'U.S. History', 'ncaa_area' => 'Social Science', 'standards' => array( 'Florida US History 9-12' ), 'course_track' => 'Social Studies', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'US History', 'grade' => 11, 'semester' => 2, 'book' => 'U.S. History', 'ncaa_area' => 'Social Science', 'standards' => array( 'Florida US History 9-12' ), 'course_track' => 'Social Studies', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 4', 'grade' => 12, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 11-12' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'English 4', 'grade' => 12, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'English', 'standards' => array( 'B.E.S.T. ELA 11-12' ), 'course_track' => 'English', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Precalculus', 'grade' => 12, 'semester' => 1, 'book' => 'Precalculus 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'Florida Precalculus 9-12' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Precalculus', 'grade' => 12, 'semester' => 2, 'book' => 'Precalculus 2e', 'ncaa_area' => 'Mathematics', 'standards' => array( 'Florida Precalculus 9-12' ), 'course_track' => 'Mathematics', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Physics 1', 'grade' => 12, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Natural/Physical Science', 'standards' => array( 'Florida Physics 1 9-12' ), 'course_track' => 'Science', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Physics 1', 'grade' => 12, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Natural/Physical Science', 'standards' => array( 'Florida Physics 1 9-12' ), 'course_track' => 'Science', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'US Government', 'grade' => 12, 'semester' => 1, 'book' => 'American Government 3e', 'ncaa_area' => 'Social Science', 'standards' => array( 'Florida US Government 9-12' ), 'course_track' => 'Social Studies', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),
		array( 'subject' => 'Economics', 'grade' => 12, 'semester' => 2, 'book' => 'Principles of Economics 3e', 'ncaa_area' => 'Social Science', 'standards' => array( 'Florida Economics with Financial Literacy 9-12' ), 'course_track' => 'Social Studies', 'grade_band' => '9-12', 'catalog_group' => 'High School Core' ),

		// Middle school core (6-8).
		array( 'subject' => 'English 6', 'grade' => 6, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. ELA Grade 6' ), 'course_track' => 'English', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'English 6', 'grade' => 6, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. ELA Grade 6' ), 'course_track' => 'English', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Mathematics 6', 'grade' => 6, 'semester' => 1, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. Math Grade 6' ), 'course_track' => 'Mathematics', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Mathematics 6', 'grade' => 6, 'semester' => 2, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. Math Grade 6' ), 'course_track' => 'Mathematics', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Earth and Space Science 6', 'grade' => 6, 'semester' => 1, 'book' => 'Astronomy 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Science Grade 6 Earth and Space' ), 'course_track' => 'Science', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Earth and Space Science 6', 'grade' => 6, 'semester' => 2, 'book' => 'Astronomy 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Science Grade 6 Earth and Space' ), 'course_track' => 'Science', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'World History 6', 'grade' => 6, 'semester' => 1, 'book' => 'World History, Volume 1', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Social Studies Grade 6 World History' ), 'course_track' => 'Social Studies', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'World History 6', 'grade' => 6, 'semester' => 2, 'book' => 'World History, Volume 1', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Social Studies Grade 6 World History' ), 'course_track' => 'Social Studies', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'English 7', 'grade' => 7, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. ELA Grade 7' ), 'course_track' => 'English', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'English 7', 'grade' => 7, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. ELA Grade 7' ), 'course_track' => 'English', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Mathematics 7', 'grade' => 7, 'semester' => 1, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. Math Grade 7' ), 'course_track' => 'Mathematics', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Mathematics 7', 'grade' => 7, 'semester' => 2, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. Math Grade 7' ), 'course_track' => 'Mathematics', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Life Science 7', 'grade' => 7, 'semester' => 1, 'book' => 'Biology 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Science Grade 7 Life Science' ), 'course_track' => 'Science', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Life Science 7', 'grade' => 7, 'semester' => 2, 'book' => 'Biology 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Science Grade 7 Life Science' ), 'course_track' => 'Science', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Civics 7', 'grade' => 7, 'semester' => 1, 'book' => 'American Government 3e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Civics Grade 7' ), 'course_track' => 'Social Studies', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Civics 7', 'grade' => 7, 'semester' => 2, 'book' => 'American Government 3e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Civics Grade 7' ), 'course_track' => 'Social Studies', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'English 8', 'grade' => 8, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. ELA Grade 8' ), 'course_track' => 'English', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'English 8', 'grade' => 8, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. ELA Grade 8' ), 'course_track' => 'English', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Pre-Algebra 8', 'grade' => 8, 'semester' => 1, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. Math Grade 8' ), 'course_track' => 'Mathematics', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Pre-Algebra 8', 'grade' => 8, 'semester' => 2, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'B.E.S.T. Math Grade 8' ), 'course_track' => 'Mathematics', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Physical Science 8', 'grade' => 8, 'semester' => 1, 'book' => 'Chemistry 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Science Grade 8 Physical Science' ), 'course_track' => 'Science', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'Physical Science 8', 'grade' => 8, 'semester' => 2, 'book' => 'Chemistry 2e', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Science Grade 8 Physical Science' ), 'course_track' => 'Science', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'US History 8', 'grade' => 8, 'semester' => 1, 'book' => 'U.S. History', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Social Studies Grade 8 US History' ), 'course_track' => 'Social Studies', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),
		array( 'subject' => 'US History 8', 'grade' => 8, 'semester' => 2, 'book' => 'U.S. History', 'ncaa_area' => 'Not Applicable', 'standards' => array( 'Florida Social Studies Grade 8 US History' ), 'course_track' => 'Social Studies', 'grade_band' => '6-8', 'catalog_group' => 'Middle School Core' ),

		// Florida EOC and FSA prep.
		array( 'subject' => 'Florida Algebra 1 EOC Prep', 'grade' => 9, 'semester' => 1, 'book' => 'Algebra and Trigonometry 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Algebra 1 EOC Blueprint' ), 'course_track' => 'Mathematics', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Algebra 1 EOC Prep', 'grade' => 9, 'semester' => 2, 'book' => 'Algebra and Trigonometry 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Algebra 1 EOC Blueprint' ), 'course_track' => 'Mathematics', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Geometry EOC Prep', 'grade' => 10, 'semester' => 1, 'book' => 'Precalculus 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Geometry EOC Blueprint' ), 'course_track' => 'Mathematics', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Geometry EOC Prep', 'grade' => 10, 'semester' => 2, 'book' => 'Precalculus 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Geometry EOC Blueprint' ), 'course_track' => 'Mathematics', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Biology 1 EOC Prep', 'grade' => 10, 'semester' => 1, 'book' => 'Biology 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Biology 1 EOC Blueprint' ), 'course_track' => 'Science', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Biology 1 EOC Prep', 'grade' => 10, 'semester' => 2, 'book' => 'Biology 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Biology 1 EOC Blueprint' ), 'course_track' => 'Science', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Civics EOC Prep', 'grade' => 7, 'semester' => 1, 'book' => 'American Government 3e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Civics EOC Blueprint' ), 'course_track' => 'Social Studies', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Civics EOC Prep', 'grade' => 7, 'semester' => 2, 'book' => 'American Government 3e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Civics EOC Blueprint' ), 'course_track' => 'Social Studies', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Grade 8 FSA/B.E.S.T. ELA Prep', 'grade' => 8, 'semester' => 1, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Grade 8 ELA FSA/B.E.S.T. Blueprint' ), 'course_track' => 'English', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Grade 8 FSA/B.E.S.T. ELA Prep', 'grade' => 8, 'semester' => 2, 'book' => 'Writing Guide with Handbook', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Grade 8 ELA FSA/B.E.S.T. Blueprint' ), 'course_track' => 'English', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Grade 8 FSA/B.E.S.T. Math Prep', 'grade' => 8, 'semester' => 1, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Grade 8 Math FSA/B.E.S.T. Blueprint' ), 'course_track' => 'Mathematics', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),
		array( 'subject' => 'Florida Grade 8 FSA/B.E.S.T. Math Prep', 'grade' => 8, 'semester' => 2, 'book' => 'Prealgebra 2e', 'ncaa_area' => 'Test Prep', 'standards' => array( 'Florida Grade 8 Math FSA/B.E.S.T. Blueprint' ), 'course_track' => 'Mathematics', 'grade_band' => 'Test Prep', 'catalog_group' => 'Florida EOC and FSA Prep' ),

		// Aviation / Aerospace / Drone STEM Pathway.
		array( 'subject' => 'Aviation Foundations', 'grade' => 9, 'semester' => 1, 'book' => 'Astronomy 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Aviation Framework', 'NGSSS Science Benchmarks' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aviation Foundations', 'grade' => 9, 'semester' => 2, 'book' => 'Astronomy 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Aviation Framework', 'NGSSS Science Benchmarks' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aerospace Science', 'grade' => 10, 'semester' => 1, 'book' => 'Astronomy 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Aerospace Framework', 'NGSSS Earth/Space Science' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aerospace Science', 'grade' => 10, 'semester' => 2, 'book' => 'Astronomy 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Aerospace Framework', 'NGSSS Earth/Space Science' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'UAS Drone Fundamentals', 'grade' => 10, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE UAS Framework', 'FAA Part 107 Knowledge Areas' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'UAS Drone Fundamentals', 'grade' => 10, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE UAS Framework', 'FAA Part 107 Knowledge Areas' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'FAA Part 107 Prep', 'grade' => 11, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'FAA Part 107 Knowledge Areas', 'Florida CTE UAS Framework' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'FAA Part 107 Prep', 'grade' => 11, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'FAA Part 107 Knowledge Areas', 'Florida CTE UAS Framework' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Private Pilot Ground School', 'grade' => 11, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'FAA Private Pilot ACS', 'Florida CTE Aviation Framework' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Private Pilot Ground School', 'grade' => 11, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'FAA Private Pilot ACS', 'Florida CTE Aviation Framework' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aviation Careers', 'grade' => 11, 'semester' => 1, 'book' => 'Introduction to Sociology 3e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Career Exploration Framework' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aviation Careers', 'grade' => 11, 'semester' => 2, 'book' => 'Introduction to Sociology 3e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Career Exploration Framework' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Flight Theory Weather and Navigation', 'grade' => 12, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'FAA Private Pilot ACS', 'NGSSS Earth/Space Science' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Flight Theory Weather and Navigation', 'grade' => 12, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'FAA Private Pilot ACS', 'NGSSS Earth/Space Science' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aerospace Engineering', 'grade' => 12, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Engineering Framework', 'NGSSS Physics Benchmarks' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aerospace Engineering', 'grade' => 12, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Engineering Framework', 'NGSSS Physics Benchmarks' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Drone Operations and Data Analysis', 'grade' => 12, 'semester' => 1, 'book' => 'Introductory Statistics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE UAS Framework', 'B.E.S.T. MATH Statistics' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Drone Operations and Data Analysis', 'grade' => 12, 'semester' => 2, 'book' => 'Introductory Statistics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE UAS Framework', 'B.E.S.T. MATH Statistics' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aviation Aerospace Capstone', 'grade' => 12, 'semester' => 1, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Capstone Framework', 'FAA Part 107 Knowledge Areas' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
		array( 'subject' => 'Aviation Aerospace Capstone', 'grade' => 12, 'semester' => 2, 'book' => 'College Physics 2e', 'ncaa_area' => 'Elective', 'standards' => array( 'Florida CTE Capstone Framework', 'FAA Part 107 Knowledge Areas' ), 'course_track' => 'Aviation/Aerospace', 'grade_band' => '9-12', 'catalog_group' => 'Aviation Aerospace Drone Pathway', 'pathway_type' => 'elective' ),
	);
}

/**
 * Get expected catalog entries for verification/reporting.
 *
 * @return array[]
 */
function llms_openstax_expected_catalog_entries() {
	$definitions = llms_openstax_course_catalog_definitions();
	$expected    = array();
	foreach ( $definitions as $row ) {
		$expected[] = array(
			'subject'  => $row['subject'],
			'grade'    => $row['grade'],
			'semester' => $row['semester'],
		);
	}
	return $expected;
}
